#!/usr/bin/env python3
"""
Script to replicate Fig. 1 in Krapp et. al., 2020.
Processes .npz files generated by the solver and plots growth rates vs wavenumber.
"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import matplotlib.lines as mlines

def build_maps(directory):

    # Maps
    map_fname = [fname for fname in os.listdir(directory) if fname.startswith("GRW_0") and fname.endswith(".npz")]
    data = np.load(directory + map_fname[0])
    drift = data["drift"]
    Am = data["Am"]
    chi = data["chi"]
    betay = data["betay"]
    betaz = data["betaz"]
    z = data["z"]
    h0 = 0.05
    r0 = 1
    invsqrteta = r0 / h0
    mn = 2.34
    mi = 30
    eps = chi * (mi / mn)
    alpha = Am / eps
    print(f"wx: {drift[0]:.2e}", "\n", 
          f"wy: {drift[1]:.2e}", "\n", 
          f"wz: {drift[2]:.2e}", "\n", 
          f"Am: {Am:.2e}", "\n",
          f"alpha: {alpha:.2e}", "\n",
          f"chi: {chi:.2e}", "\n",
          f"eps: {eps:.2e}", "\n",
          f"betay: {betay:.2e}", "\n",
          f"betaz: {betaz:.2e}")

    # Load data
    kx  = np.load(directory+"KX_0.npz")
    kz  = np.load(directory+"KZ_0.npz")
    Kkx = kx["arr_0"]
    Kkz = kz["arr_0"]
    MAP = data["data"]

    # plotting
    fig = plt.figure(figsize=(6,6))
    MAP[MAP<=1e-3] = np.nan
    axes = plt.subplot(1,1,1)

    im1 = axes.pcolormesh(Kkx, Kkz, np.log10(MAP), shading='auto', cmap='plasma', vmin=-3, vmax=0)
    axes.set_xscale('log')
    axes.set_yscale('log')
    axes.set_xlabel(r'$K_x\eta r_0$')
    axes.set_ylabel(r'$K_z\eta r_0$')
    ax_ins = inset_axes(axes, width="35%", height="3%", loc='upper left', 
                    bbox_to_anchor=(0.05, -0.20, 1, 1), 
                    bbox_transform=axes.transAxes, borderpad=0)
    cbar = fig.colorbar(im1, cax=ax_ins, orientation='horizontal', extend='both')
    cbar.set_label(r'$\log_{10}(\sigma/\Omega_0)$', labelpad=-40, y=1.5) # Etiqueta arriba
    ax_ins.xaxis.set_ticks_position('bottom') # Ticks abajo
    ax_ins.tick_params(labelsize=8)

    # Resonance lines
    KX, KZ = np.meshgrid(Kkx, Kkz)
    res_cond = KX * invsqrteta * drift[0] + KZ * invsqrteta * drift[2] - np.abs((KZ)/(np.sqrt(KX**2 + KZ**2)))
    cs = axes.contour(KX, KZ, res_cond, levels=[0], colors='k', linestyles='dashed', linewidths=1, label="Resonant Modes")

    line_proxy = mlines.Line2D([], [], color='k', linestyle='--', 
                            linewidth=1.5, label='Resonant Modes')

    axes.legend(handles=[line_proxy], loc='upper left', 
                bbox_to_anchor=(0.05, 0.95), frameon=False)
    
    output_path = "./figures/"
    if not os.path.exists(output_path):
        os.makedirs(output_path, exist_ok=True)
        print(f"Created directory: {output_path}")


    z = z / h0
    if z==0.5:
        z_label = "0p5"
    else:
        z_label = f"{int(z)}"

    plt.savefig(os.path.join(output_path, f"Settling_{z_label}H.png"), dpi=300)
    plt.savefig(os.path.join(output_path, f"Settling_{z_label}H.pdf"), bbox_inches='tight')
    print("Map saved to:", os.path.join(output_path, f"Settling_{z_label}H.png"))

def main():
    if len(sys.argv) < 2:
        print(" ")
        print("Run the script as:")
        print("python3 plot_map.py <directory>")
        print("=================================================")
        print(" ")
        exit()

    dir = sys.argv[1]

    build_maps(dir)

if __name__ == "__main__":
    main()