#!/usr/bin/env python3
"""
Script for instability analysis and eigenvalue visualization.
Processes .npz files generated by simulation and plots growth rates.
"""

import os
import re
import sys
import numpy as np
import matplotlib.pyplot as plt
import json
import gc
import math
from matplotlib.lines import Line2D

r0 = 1.0
h0 = 0.05 * r0
invsqrteta = r0 / h0

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

def get_mode(outputdir):
    parfile = open(outputdir+"variables.par","r")
    for line in parfile:
        if line.rfind("SOUNDSPEED") >= 0:
            cs = float(line.split()[1])
        if line.rfind("BETA") >= 0:
            beta = float(line.split()[1])
        if line.rfind("OMEGAFRAME") >= 0:
            om0 = float(line.split()[1])
        if line.rfind("ZMIN") >= 0:
            zmin = float(line.split()[1])
        if line.rfind("ZMAX") >= 0:
            zmax = float(line.split()[1])
            
    #It only works if mu0 = rho0 = 1!
    kmode = 2*np.pi/(zmax-zmin)*cs*np.sqrt(2/beta)/om0; 
    # print( cs, beta, zmin, zmax, "==> ktilde-mode =", kmode)
    
    return kmode

def get_file_path(directory, prefix, extension=".npz"):
    """
    Search for a file in the directory that starts with the given prefix.
    Returns the full path or None if not found.
    """
    for filename in os.listdir(directory):
        if filename.startswith(prefix) and filename.endswith(extension):
            return os.path.join(directory, filename)
    return None

def optimal_distribution(n):
    """
    Calculate the optimal arrangement (rows, columns) for n plots.
    Prioritizes a square or landscape rectangular shape.
    """
    if n <= 0:
        return 0, 0
        
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    
    return rows, cols

def curves(dir, savefig=False, overwrite=False):
    kz_path = get_file_path(dir, "KZ_")
    
    if not kz_path:
        print("Error: KZ_ file not found.")
        sys.exit(1)
        
    kz_values = np.load(kz_path)["arr_0"]
    map_fnames = [map_fname for map_fname in os.listdir(dir) if map_fname.startswith("GRW_0") and map_fname.endswith(".npz")]

    chi_values = set()

    for map_fname in map_fnames:
        split_fname = map_fname.rstrip(".npz").split("_")
        # Group by chi value
        try:
            chi_ = split_fname[3]
            chi_values.add(chi_)
        except IndexError:
            continue
    
    chi_values = [chi for chi in chi_values if "5e" not in chi] # Exclude chi=5eX values for clarity
    chi_values = sorted(chi_values)

    dummy = [fname for fname in map_fnames if f"chi_{chi_values[0]}_" in fname]

    configs = set()
    for fname in dummy:
        betay = fname.split(".")[0].split("_")[5]
        betaz = fname.split(".")[0].split("_")[7]
        configs.add((betay, betaz))
    configs = sorted(configs, key=lambda x: (float(x[0]), float(x[1])))
    
    len_datasets = len(configs)

    nrows, ncols = optimal_distribution(len_datasets)
    fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(5*ncols, 4*nrows))

    if len_datasets == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    for i, (ax, config) in enumerate(zip(axes, configs)):
        betay, betaz = config
        for chi in chi_values:
            # Get filenames from list matching the chi value
            string = f"chi_{chi}_betay_{betay}_betaz_{betaz}"
            matched_fnames = [fname for fname in map_fnames if string in fname]
            
            if not matched_fnames:
                continue
            print(matched_fnames)
            map_fname = matched_fnames[0]
            
            data_nodrift = np.load(os.path.join(dir, map_fname), allow_pickle=True)
                
            eigval = data_nodrift["data"][:,0]

            Am = data_nodrift["Am"]
            chi_val = data_nodrift["chi"]
            betay_val = data_nodrift["betay"]
            betaz_val = data_nodrift["betaz"]
            drift = data_nodrift["drift"]
            
            eps = chi_val # mi = mn = 1, so chi = eps
            
            # Plotting
            x_data = kz_values * invsqrteta * np.sqrt(2.0 / betaz_val) * np.sqrt((1.0 + chi_val)/(1.0 + eps))
            y_data = eigval
            ax.plot(x_data, y_data, 'k-', label = f"Analytical")

            z = [ 0.3974, 0.0911,
                0.0274 , 0.0223,
                0.012, 0.0115]

            ny = 64
            nz = 64
            ninterm = 2
            dt      = 0.1

            #Now we put the simulations on top of it
            for j in range(len(z)):
                outputdir = "fargo3d/outputs/output{:d}/".format(j)
                mode = get_mode(outputdir)
                #We will use "By" to measure the growth rate.
                maxv = []
                time = []
                for i in range(20):
                    by = np.fromfile(outputdir+"by{:d}.dat".format(i)).reshape(nz,ny)
                    time.append(i*dt*ninterm)
                    #Here, for simplicity, we use the evloution of the max value of
                    #the magnetic field to measure the growth rate. Note that you can
                    #also do it in the Fourier space.
                    maxv.append(by.max())
                #We get the growth rate with linear fit
                a,b = np.polyfit(time, np.log(maxv), 1)
                #We plot the measured point over the dispertion relation
                if j==0:
                    ax.plot(mode,a,'o', label = f"Fargo3D", c='tab:blue', fillstyle='none')
                else:
                    ax.plot(mode,a,'o',c='tab:blue', fillstyle='none') #This is the mode that we have simulated
            ax.legend()
        
        if i == 0:
            leg_local = ax.legend(title="AD Elsasser number")
            ax.add_artist(leg_local)

        ax.set_ylabel(r"$Im(\omega/\Omega_0)$")
        ax.set_xlabel(r"$k_zv_{A,z}/\Omega_0$")
        
        ax.set_xlim(left = 0.01, right = 4)
        ax.set_ylim(top = 1.0, bottom = -0.05)
        ax.set_title(fr"$\beta_y$={betay_val:.0e}, $\beta_z$={betaz_val:.0e}, $A_m$={Am:.2e}")
        
        ax.axhline(0, color='k', lw=0.5, ls='--')
        
        # Save the handles of the last plotted dataset for the global legend
        if i == len_datasets - 1:
            lines_labels = ax.get_legend_handles_labels()

        # Hide empty axes if the grid is larger than the datasets
        for j in range(len_datasets, len(axes)):
            axes[j].axis('off')
        
    
    z = dir.split("_")[-1]

    if "/" in z:
        z = z.split("/")[0]

    if savefig:
        output_path = "./figures/"
        if not os.path.exists(output_path):
            os.makedirs(output_path, exist_ok=True)
            print(f"Created directory: {output_path}")
        
        folders = [f for f in os.listdir(output_path) if os.path.isdir(os.path.join(output_path, f))]
        index = []

        for f in folders:
            if f.startswith("test_"):
                try:
                    num = int(f.replace("test_", ""))
                    index.append(num)
                except ValueError:
                    continue
        
        if not index:
            next_index = 0
        else:
            last_index = max(index)
            last_folder_path = os.path.join(output_path, f"test_{last_index:02d}")
            check_file = os.path.join(last_folder_path, f"GrowthRates_{z}.png")
            if os.path.exists(check_file) and overwrite==False:
                next_index = last_index + 1
            else:
                next_index = last_index

        new_path = os.path.join(output_path, f"test_{next_index:02d}")
        os.makedirs(new_path, exist_ok=True)

        plt.savefig(os.path.join(new_path, f"GrowthRates_{z}.png"), dpi=300)
        plt.savefig(os.path.join(new_path, f"GrowthRates_{z}.pdf"), bbox_inches='tight')

        print("Map saved to:", os.path.join(new_path, f"GrowthRates_{z}.png"))

def extract(list, keyw):
    return [float(line.split()[1]) for line in list if keyw in line][0]

def max_growth_rate(an_dir, fargo_dir):
    # Extract FARGO3D parameters
    with open(os.path.join(fargo_dir, "variables.par"), "r") as var:
        vars = var.readlines()

    Ninterm = extract(vars, "NINTERM")
    Ntot    = extract(vars, "NTOT")
    DT      = extract(vars, "DT")
    ny      = extract(vars, "NY")
    nz      = extract(vars, "NZ")
    zmin    = extract(vars, "ZMIN")
    zmax    = extract(vars, "ZMAX")
    cs      = extract(vars, "SOUNDSPEED")
    beta    = extract(vars, "BETA")
    om0     = extract(vars, "OMEGAFRAME")

    Nout  = int(Ntot // Ninterm)
    kmode = 2*np.pi/(zmax-zmin)*cs*np.sqrt(2/beta)/om0

    kz_path = get_file_path(an_dir, "KZ_")
    
    if not kz_path:
        print("Error: KZ_ file not found.")
        sys.exit(1)
        
    kz_values = np.load(kz_path)["arr_0"]
    map_fnames = [map_fname for map_fname in os.listdir(an_dir) if map_fname.startswith("GRW_0") and map_fname.endswith(".npz")]
    map_fnames = [map_fname for map_fname in map_fnames if "chi_5e" not in map_fname] # Exclude chi=5eX values for clarity

    max_growth_parameters = {"omega": 0.0, "k_z": None, "chi": None, "Am":None, "betay": None, "betaz": None}
    max_growth_eigvector = {"omega": None,"gasdens": None, "gasvx":None, "gasvy": None, "gasvz": None, "bx": None, "by": None}

    map_fname = map_fnames[0]

    vec_fname = map_fname.replace("GRW_", "VEC_")

    grw = np.load(os.path.join(an_dir, map_fname), allow_pickle=True)
    osc = np.load(os.path.join(an_dir, map_fname.replace("GRW_", "OSC_")), allow_pickle=True)
    vec = np.load(os.path.join(an_dir, vec_fname), allow_pickle=True)

    GRW = grw
    OSC = osc
    VEC = vec

    chi_val = GRW["chi"]
    Am_val = GRW["Am"]
    betay_val = GRW["betay"]
    betaz_val = GRW["betaz"]
    eps = chi_val

    idx_z = 0
    idx_x = 0
    kzvA_Omega = kz_values * invsqrteta * np.sqrt(2.0 / betaz_val) * np.sqrt((1.0 + chi_val)/(1.0 + eps))

    max_growth_parameters["omega"] = GRW["data"][idx_z, idx_x]
    max_growth_parameters["k_z"] = kz_values[idx_z]
    max_growth_parameters["chi"] = GRW["chi"]
    max_growth_parameters["Am"] = GRW["Am"]
    max_growth_parameters["betay"] = GRW["betay"]
    max_growth_parameters["betaz"] = GRW["betaz"]

    max_growth_eigvector["gasdens"] = VEC["data"][idx_z, idx_x, :][8].view(complex).flatten()
    max_growth_eigvector["omega"]   = OSC["data"][idx_z, idx_x] + 1j * GRW["data"][idx_z, idx_x]
    max_growth_eigvector["gasvx"]   = VEC["data"][idx_z, idx_x, :][0].view(complex).flatten()
    max_growth_eigvector["gasvy"]   = VEC["data"][idx_z, idx_x, :][1].view(complex).flatten()
    max_growth_eigvector["gasvz"]   = VEC["data"][idx_z, idx_x, :][2].view(complex).flatten()
    max_growth_eigvector["bx"]      = VEC["data"][idx_z, idx_x, :][6].view(complex).flatten()
    max_growth_eigvector["by"]      = VEC["data"][idx_z, idx_x, :][7].view(complex).flatten()

    max_growth_eigvector["omega"]   *= om0

    return max_growth_parameters, max_growth_eigvector


def fargo(an_dir, fargo_dir):
    # outputdir = "fargo3d/outputs/output4/"   #From the .par file
    Ninterm   = 2                                #From the .par file
    ny        = 64                               #From the .par file
    nz        = 64                               #From the .par file
    DT        = 0.1                              #From the .par file
    Ntot      = 160                              #From the .par file
    Nout      = Ntot // Ninterm
    zmin = 0.0
    zmax = 0.012

    for key in ["gasvx", "gasvy", "gasvz", "bx", "by"]:
        
        maxv = []
        time = []
        for i in range(Nout):
            val = np.fromfile(fargo_dir+"{:s}{:d}.dat".format(key,i)).reshape(nz,ny)
            background = np.fromfile(fargo_dir+"{:s}{:d}.dat".format(key,i)).reshape(nz,ny).mean(axis=0)
            time.append(i*DT*Ninterm)
            maxv.append((val - background).max())

        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.plot(time, maxv, 'ro', label=f"Fargo3D")
        pars, eigvectors = max_growth_rate(an_dir, fargo_dir)

        comp_eigvec = eigvectors[key]
        growth_rate = eigvectors["omega"]
        kkz = pars["k_z"]
        kz = 2*np.pi/(zmax-zmin)
        z = 0.012
        t = np.linspace(time[0], time[-1], len(time))
        # eigvec = (comp_eigvec.real * np.cos(kz * z + growth_rate.real * t) - comp_eigvec.imag * np.sin(kz * z + growth_rate.real * t)) * np.exp(growth_rate.imag * t)
        # eigvec = np.abs(comp_eigvec) * np.exp(growth_rate.imag * t)
        A = 1.0e-06
        N = np.sqrt(np.abs(eigvectors["gasdens"])**2 + np.abs(eigvectors["gasvx"])**2 + np.abs(eigvectors["gasvy"])**2 + np.abs(eigvectors["gasvz"])**2 + np.abs(eigvectors["bx"])**2 + np.abs(eigvectors["by"])**2)
        eigvec = (A/N) * np.abs(comp_eigvec) * np.exp(growth_rate.imag * t)

        ax.plot(time, eigvec, 'k--', label=f"Analytical")
        ax.set_xlabel("t")
        ax.set_ylabel("Amplitude")
        ax.set_yscale("log")
        ax.legend(loc='best')
        plt.savefig(f"figures/comp_{key}.png", dpi=300)



def main():
    if len(sys.argv) < 2:
        print("Usage: python growth_rates.py <directory>")
        sys.exit(1)

    dir = sys.argv[1]

    # curves(dir, savefig=True, overwrite=True)
    # max_growth_rate(dir,"fargo3d/outputs/output4/")
    fargo(dir, "fargo3d/outputs/output4/")
    gc.collect()
    

if __name__ == "__main__":
    main()