#!/usr/bin/env python3
"""
Script to replicate Fig. 9 in Pessah & Psaltis (2005).
Processes .npz files generated by the solver and plots growth rates vs wavenumber.
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import gc

def get_file_path(directory, prefix, extension=".npz"):
    """
    Search for a file in the directory that starts with the given prefix.
    Returns the full path or None if not found.
    """
    for filename in os.listdir(directory):
        if filename.startswith(prefix) and filename.endswith(extension):
            return os.path.join(directory, filename)
    return None

def curves(dir):
    # Constants
    r0, h0 = 1, 0.05
    mn, mi = 2.34, 30
    invsqrt_eta = r0 / h0

    # Get KZ values from file
    kz_path = get_file_path(dir, "KZ_")
    
    if not kz_path:
        print("Error: KZ_ file not found.")
        sys.exit(1)
        
    kz_values = np.load(kz_path)["arr_0"]

    # Get maps file names in folder
    map_fnames = [map_fname for map_fname in os.listdir(dir) if map_fname.startswith("GRW_0") and map_fname.endswith(".npz")]

    # Group by ratio value
    ratio_values = set()
    for map_fname in map_fnames:
        split_fname = map_fname.rstrip(".npz").split("_")
        try:
            ratio_ = float(split_fname[3])
            ratio_values.add(ratio_)
        except (IndexError, ValueError):
            continue
    ratio_values = sorted(ratio_values)[::-1]
    
    # Plotting
    fig, ax = plt.subplots(figsize=(6, 5.5))
    for i, ratio in enumerate(ratio_values):
        # Get filenames from list matching the cs2/vA2 ratio values
        string = f"ratio_{ratio:.2e}"
        matched_fnames = [fname for fname in map_fnames if string in fname]
        
        if not matched_fnames:
            continue
        map_fname = matched_fnames[0]
        
        data = np.load(os.path.join(dir, map_fname), allow_pickle=True)

        # File parameters    
        eigval = data["data"][:,0]
        chi    = data["chi"]
        betaz  = data["betaz"]
        z      = data["z"]

        # Variables
        eps = chi * (mi / mn)
        
        # Plot
        x_data = kz_values * invsqrt_eta * np.sqrt(2.0 / betaz) * np.sqrt((1.0 + chi)/(1.0 + eps))
        y_data = eigval
        ax.plot(x_data, y_data, label = f"$c_s^2/v_A^2$={ratio:.5f}", ls=":", color="k")

        idx_max = np.argmax(y_data)
        x_peak = x_data[idx_max]
        y_peak = y_data[idx_max]
        if i==0:
            label_text = f"$c_s^2/v_A^2={float(ratio)}$"
        elif ratio == 0.0006:
            label_text = r"$6\times10^{-4}$"
        else:
            label_text = f"{float(ratio)}"
        ax.text(x_peak, y_peak - 0.015, label_text, 
                fontsize=8, ha='center', va='bottom', color='k',
                bbox=dict(facecolor='white', edgecolor='none', pad=1.0))
    
    # Plot settings
    ax.set_ylim(top = 0.8, bottom = 0.0)
    ax.set_xlim(left = 0.0  , right = 4.0)
    ax.set_xlabel(r"$k_z v_{Az} / \Omega_0$", fontsize=14)
    ax.set_ylabel(r"$Im(\omega/\Omega_0)$", fontsize=14)
    ax.tick_params(which='both', direction='in', top=True, right=True, labelsize=11)
    ax.minorticks_on()
    ax.tick_params(which='minor', direction='in', top=True, right=True)
    plt.tight_layout()

    # Save parameters
    output_path = "./figures/"
    if not os.path.exists(output_path):
        os.makedirs(output_path, exist_ok=True)
        print(f"Created directory: {output_path}")

    # Labeling the figure with z/h0 value
    z = z / h0
    if z==0.5:
        z_label = "0p5"
    else:
        z_label = f"{int(z)}"

    # Save the figure
    plt.savefig(os.path.join(output_path, f"PnP2005_{z_label}H.png"), dpi=300)
    plt.savefig(os.path.join(output_path, f"PnP2005_{z_label}H.pdf"), bbox_inches='tight')
    print("Map saved to:", os.path.join(output_path, f"PnP2005_{z_label}H.png"))


def main():
    if len(sys.argv) < 2:
        print("Usage: python plot_map.py <growth rates directory>")
        sys.exit(1)

    dir = sys.argv[1]

    curves(dir)
    gc.collect()
    

if __name__ == "__main__":
    main()