#!/usr/bin/env python3
"""
Script for instability analysis and eigenvalue visualization.
Processes .npz files generated by simulation and plots growth rates.
"""

import os
import re
import sys
import numpy as np
import matplotlib.pyplot as plt
import json
import gc
import math
from matplotlib.lines import Line2D

def get_file_path(directory, prefix, extension=".npz"):
    """
    Search for a file in the directory that starts with the given prefix.
    Returns the full path or None if not found.
    """
    for filename in os.listdir(directory):
        if filename.startswith(prefix) and filename.endswith(extension):
            return os.path.join(directory, filename)
    return None

def optimal_distribution(n):
    """
    Calculate the optimal arrangement (rows, columns) for n plots.
    Prioritizes a square or landscape rectangular shape.
    """
    if n <= 0:
        return 0, 0
        
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    
    return rows, cols

def curves(dir, savefig=False, overwrite=False):
    kz_path = get_file_path(dir, "KZ_")
    
    if not kz_path:
        print("Error: KZ_ file not found.")
        sys.exit(1)
        
    kz_values = np.load(kz_path)["arr_0"]
    map_fnames = [map_fname for map_fname in os.listdir(dir) if map_fname.startswith("GRW_0") and map_fname.endswith(".npz")]

    chi_values = set()

    for map_fname in map_fnames:
        split_fname = map_fname.rstrip(".npz").split("_")
        # Group by chi value
        try:
            chi_ = split_fname[3]
            chi_values.add(chi_)
        except IndexError:
            continue
    
    chi_values = [chi for chi in chi_values if "5e" not in chi] # Exclude chi=5eX values for clarity
    chi_values = sorted(chi_values)

    dummy = [fname for fname in map_fnames if f"chi_{chi_values[0]}_" in fname]

    configs = set()
    for fname in dummy:
        betay = fname.split(".")[0].split("_")[5]
        betaz = fname.split(".")[0].split("_")[7]
        configs.add((betay, betaz))
    configs = sorted(configs, key=lambda x: (float(x[0]), float(x[1])))
    
    len_datasets = len(configs)

    nrows, ncols = optimal_distribution(len_datasets)
    fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(5*ncols, 4*nrows))

    if len_datasets == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    for i, (ax, config) in enumerate(zip(axes, configs)):
        betay, betaz = config
        for chi in chi_values:
            # Get filenames from list matching the chi value
            string = f"chi_{chi}_betay_{betay}_betaz_{betaz}"
            matched_fnames = [fname for fname in map_fnames if string in fname]
            
            if not matched_fnames:
                continue
            map_fname = matched_fnames[0]
            data_drift = np.load(os.path.join(dir, map_fname), allow_pickle=True)
            data_limit = np.load(os.path.join("limit_"+dir, map_fname), allow_pickle=True)
                
            eigval_drift = data_drift["data"][:,0]
            eigval_limit = data_limit["data"][:,0]

            Am = data_drift["Am"]
            chi_val = data_drift["chi"]
            betay_val = data_drift["betay"]
            betaz_val = data_drift["betaz"]
            drift = data_drift["drift"]
            
            # Plotting
            ax.plot(kz_values, eigval_drift, label = f"$A_m$={Am:.2e}")
            color = ax.get_lines()[-1].get_color()
            ax.scatter(kz_values, eigval_limit, c = color)
        
        if i == 0:
            leg_local = ax.legend(title="AD Elsasser number")
            ax.add_artist(leg_local)

        col = i % ncols
        row = i // ncols

        # Only add ylabel if we are in the first column
        if col == 0:
            ax.set_ylabel(r"$Re(\omega/\Omega_0)$")
        # Only add xlabel if we are in the last row
        if row == nrows - 1:
            ax.set_xlabel(r"$k_z\eta r_0$")
        
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_ylim(bottom = -0.05)
        # print(ax.get_ylim())
        ax.set_title(fr"$\beta_y$={betay_val:.0e}, $\beta_z$={betaz_val:.0e}")
        
        ax.axhline(0, color='k', lw=0.5, ls='--')
        
        x0 = 0.05
        ax.axvline(x0, color='gray', lw=0.5, ls=':')  # Example threshold line at k_z * eta * r0 = 0.05

        y_text = 0.9 * ax.get_ylim()[1]
        ax.text(x0 * 1.05, y_text, r'$k_z = 1/H$', rotation=90, va='top', ha='left', color='gray')

        # Save the handles of the last plotted dataset for the global legend
        if i == len_datasets - 1:
            lines_labels = ax.get_legend_handles_labels()

        # Hide empty axes if the grid is larger than the datasets
        for j in range(len_datasets, len(axes)):
            axes[j].axis('off')
        
        # plt.tight_layout(rect=[0, 0.08, 1, 1])
        
        # Leave space at the bottom for the legend
        # plt.subplots_adjust(bottom=0.06)

    legend_elements = [
        # Height
        # Line2D([0], [0], color=color_z0, lw=2, label='z = 0'),
        # Line2D([0], [0], color=color_zH, lw=2, label='z = H'),

        # Case
        Line2D([0], [0], color='gray', lw=2, ls='-', label='Classical MRI'),
        Line2D([0], [0], color='gray', lw=2, ls='--', label='Ion-Neutral drift')
        ]

    # Global legend
    fig.legend(handles=legend_elements, 
                loc='lower center', 
                bbox_to_anchor=(0.5, 0.01), 
                ncol=4,
                frameon=False)
    
    z = dir.split("_")[-1]

    if "/" in z:
        z = z.split("/")[0]

    if savefig:
        output_path = "./figures/"
        if not os.path.exists(output_path):
            os.makedirs(output_path, exist_ok=True)
            print(f"Created directory: {output_path}")
        
        folders = [f for f in os.listdir(output_path) if os.path.isdir(os.path.join(output_path, f))]
        index = []

        for f in folders:
            if f.startswith("test_"):
                try:
                    num = int(f.replace("test_", ""))
                    index.append(num)
                except ValueError:
                    continue
        
        if not index:
            next_index = 0
        else:
            last_index = max(index)
            last_folder_path = os.path.join(output_path, f"test_{last_index:02d}")
            check_file = os.path.join(last_folder_path, f"GrowthRates_{z}.png")
            if os.path.exists(check_file) and overwrite==False:
                next_index = last_index + 1
            else:
                next_index = last_index

        new_path = os.path.join(output_path, f"test_{next_index:02d}")
        os.makedirs(new_path, exist_ok=True)

        plt.savefig(os.path.join(new_path, f"GrowthRates_{z}.png"), dpi=300)
        plt.savefig(os.path.join(new_path, f"GrowthRates_{z}.pdf"), bbox_inches='tight')

        print("Map saved to:", os.path.join(new_path, f"GrowthRates_{z}_limit.png"))

def main():
    if len(sys.argv) < 2:
        print("Usage: python growth_rates.py <directory>")
        sys.exit(1)

    dir = sys.argv[1]

    curves(dir, savefig=True, overwrite=False)
    # max_growth_rate(dir)
    gc.collect()
    

if __name__ == "__main__":
    main()